### ISSUE TITLE
[Physics.PhysX] cleaning the mesh failed

### ISSUE THREAD

**Issue by CHenBuCHen** [Eldemarkki/Marching-Cubes-Terrain#22]
I don't know this my promble or is a bug or something else. 
This appears in "Heightmap World Example" .    
I open with Unity2019.3.2f1.
And I really like this project. I appreciate your work.

![image](https://user-images.githubusercontent.com/16070112/77227709-34f9d280-6bbd-11ea-8150-c252b2647483.png)

**Comment by Eldemarkki** [comment]
I’m aware of this bug, but currently I don’t really have ideas as to what is causing it. The most logical reason in my opinion is something to do with the density calculation in HeightmapDensityCalculationJob.cs. I will probably try to fix this soon.

**Comment by Eldemarkki** [comment]
I have figured out what is causing this, but haven't thought of a solution yet. It is caused when a chunk's only mesh is a tiny edge. It can be seen in this video: [https://vimeo.com/399672667](https://vimeo.com/399672667). The grey box (which can be barely seen) is the chunk that is causing the error. At 8 seconds in the video, I'm showing the edge that is inside the error-chunk causing the problem.

**Comment by CHenBuCHen** [comment]
Hello,I fork you project ,and create my tools based on it. In my project I can editor terrain in editor mode and save chunk states ,serialize densities. You can use "tools/Create Voxel World" create terrain. 
Tools are simple ,not easy to use. I'm thinking about  translate  FBX/OBJ to  terrain .
The problem is this, I want to reproduce bug in my tools, but it does not appear. I notice in your project when amplitude = 30, 34, 40,60,68. error message appear(I had try amplitude =1-70).  In my tools error messages does not appear. 
(For example when amplitude  = 30 , in your project chunk_4_0_11'mesh has 30 verts 10tris, in my project chunk_4_0_11'mesh has 0 verts 0tris)
I don't  know what's happend, and what's the difference between this.I'm not sure if I solved the bug or if the bug will appear at other values /*  I'm a terrible programmer,with ugly code.  :(  */ .  I hope this can help .https://github.com/CHenBuCHen/Marching-Cubes-Terrain 
![微信截图_20200330233243](https://user-images.githubusercontent.com/16070112/77936077-f4006d00-72e4-11ea-8826-273f41fc7424.png)
![微信截图_20200330233300](https://user-images.githubusercontent.com/16070112/77936130-04b0e300-72e5-11ea-9c0c-fb7b9851a778.png)
![微信截图_20200330233459](https://user-images.githubusercontent.com/16070112/77936136-08446a00-72e5-11ea-8884-d75f275fecf0.png)
![微信截图_20200330233534](https://user-images.githubusercontent.com/16070112/77936143-0a0e2d80-72e5-11ea-81a6-f676c44a196c.png)

**Comment by Eldemarkki** [comment]
Fixed in develop branch

**Comment by Eldemarkki** [comment]
Fixed in master
