### ISSUE TITLE
Increase Procedural Terrain Generation Performance

### ISSUE THREAD

**Issue by ThisUserIsNobody** [Eldemarkki/Marching-Cubes-Terrain#35]
One thing would be really nice to improve is the procedural terrain generation performance. Currently it's pretty bad with really long lags whenever a new chunk is created.
One way I can think of is using Compute Shaders, Although, maybe there are better ways I'm not sure.

**Comment by Eldemarkki** [comment]
Yep, I also want this! Did you try this with the master or develop branch? I think develop is faster due to the optimizations I’ve done, but haven’t yet merged to master. Also, when you build it, everything will be faster.

**Comment by ThisUserIsNobody** [comment]
I have tried the master branch. I will take a look at the develop as well :) Really cool project btw!

**Comment by Eldemarkki** [comment]
As there is no real way to measure how far this is in progress, I'm closing this issue. Performance improvements are an ongoing thing with no end point.
