### ISSUE TITLE
Convert this project into a Unity Package Manager package

### ISSUE THREAD

**Issue by Eldemarkki** [Eldemarkki/Marching-Cubes-Terrain#38]
This would allow people to import this only by adding a dependency in the manifest.json file. Unfortunately, currently UPM doesn't seem to support examples, so the scenes would have to go.

**Comment by Siccity** [comment]
You can have your example scenes in a separate branch.

**Comment by Eldemarkki** [comment]
https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4

> "You can include a list of samples (scene + assets) to demonstrate the package usage."

It seems like UPM actually supports examples, and more importantly, examples with scenes. I'm wondering what the [OpenUPM](https://openupm.com/) is, and is it officially supported by Unity, or what? Doesn't seem to be, but I don't know.

More: https://medium.com/openupm

**Comment by Eldemarkki** [comment]
Closing this issue, because I feel like this project isn't suitable to be a package - it isn't "plug-and-play"-y enough, and it would be very difficult to make it that way.
